name: Container Build and Trigger Deploy ## comment
on:
  push:
    branches:
      - acr 

env:
  CODE_SRC_FOLDER: tracktor
  REGISTRY: mazenatefdevk8sk8sreg42h.azurecr.io
  REPOSITORY: tracktor
  LOGIN_USER: ${{ secrets.AZURE_CLIENT_ID }}
  LOGIN_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  DEV_PAYLOAD: '{"registry": "bidmaindevk8sk8sreg573m.azurecr.io","repository": "tracktor","value_file": "./helm/value-dev.yml","cluster": "bid-main-dev-k8s-cluster-main-9wj4","resource_group": "bid-main-dev-k8s-rg-3gvs","release": "tracktor","namespace": "default","timeout": "10m"}'
  PROD_PAYLOAD: '{"registry": "bidmaindevk8sk8sreg573m.azurecr.io","repository": "tracktor","value_file": "./helm/value-prod.yml","cluster": "bid-main-dev-k8s-cluster-main-9wj4","resource_group": "bid-main-dev-k8s-rg-3gvs","release": "tracktor","namespace": "default","timeout": "10m"}'

jobs:

  build:
    name: Build Tracktor
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0

      - name: Azure Login
        env:
          USER: ${{ secrets.AZURE_CLIENT_ID }}
          SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TENANT: ${{ secrets.AZURE_CLIENT_TENANT }}
        run: |
          az login --service-principal -u ${USER} -p ${SECRET} --tenant ${TENANT}
          az account set --subscription="012901f9-e5ca-44a8-b241-f4a383710f91"

      - name: ACR Login
        run: |
          az acr login -n mazenatefdevk8sk8sreg42h
      

      - name : List all tags in the ACR
        id : tags
        run : |
          echo "::set-output name=TAGI::$(echo $(az acr repository show-tags --name ${REGISTRY} --repository ${REPOSITORY}))"
         
      - name : check tags
        run : |
          echo $TAGI
      - name : check contain 
       # if: contains(env.TAGS, '10b1ac5')
        if: contains( ${{ steps.tags.outputs.TAGI }},'10b1ac5') 
        run : az acr import -n ${REGISTRY} --source ${REGISTRY}/${REPOSITORY}:10b1ac5 --image ${REPOSITORY}:${GITHUB_SHA:1:7}


 
 ##echo "::set-output name=tags::$(az acr repository show-tags --name ${REGISTRY} --repository ${REPOSITORY})"
      
    ##working##echo "TAGS=$(echo $(az acr repository show-tags --name ${REGISTRY} --repository ${REPOSITORY}))" >> $GITHUB_ENV
