name: Container Build and Trigger Deploy ## comment
on:
  push:
    branches:
      - devvv
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Trigger Deployment'
        requiered: true
        default: 'false'

env:
  CODE_SRC_FOLDER: tracktor
  REGISTRY: mazenatefdevk8sk8sreg42h.azurecr.io
  REPOSITORY: tracktor
  DEV_PAYLOAD: '{"value_file": "./helm/values-dev.yaml","cluster": "mazen-atef-dev-k8s-cluster-main-x0l6","resource_group": "mazen-atef-dev-k8s-rg-51gx","release": "tracktor","namespace": "default","timeout": "10m"}'
jobs:

  build:
    name: Build Tracktor
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
        with: 
          fetch-depth: 0

      - name: Prepare SSH-Keys
        uses: shimataro/ssh-key-action@v2.0.3
        with:
          key: ${{ secrets.CROSS_PULL_GIT_ACTIONS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Generate Image Tags "dev"
        run: |
          echo "DEV_TAG=$(echo ${GITHUB_SHA:1:7})" >> $GITHUB_ENV
      # step to check .. to be removed.
      - name: check "dev" Tag
        run: |
          echo $DEV_TAG
      # Call the Docker build script with the correct variables (depending on the branch name)
      - name: Image Build and Push "dev"
        env:
          LOGIN_USER: ${{ secrets.AZURE_CLIENT_ID }}
          LOGIN_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
         bash .github/scripts/docker_build_and_push.sh
      
  deploy:
    name: Trigger Testing Deployment
    runs-on: ubuntu-latest
    needs: build
    if: ${{ endsWith(github.ref, '/dev') || github.event.inputs.deploy == 'true' }}
    steps:
      - name: Generate Payload
        id: set-post-options
        run: |
          echo "::set-output name=environment::$(echo 'testing')"
          echo "::set-output name=payload::$(echo ${DEV_PAYLOAD})"

      - name: Create Deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          mediaType: |
            previews:
              - flash
          ref: ${{ github.sha }}
          environment: ${{ steps.set-post-options.outputs.environment }}
          payload: ${{ steps.set-post-options.outputs.payload }}
          auto_merge: false
          required_contexts: '["Build Tracktor"]'
          description: Automatic deployment triggered from Pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
          # Needs a service user token because the normal GitHub Action token is not allowed to trigger other workflows:
          # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
