name: Prepare for production Deploy ## comment#
on:
  push:
    branches:
      - devvv

env:
  REGISTRY: mazenatefdevk8sk8sreg42h.azurecr.io
jobs:

  build:
    name: Generate a production Image 
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
        with: 
          fetch-depth: 0

      - name: git log 
        run: git log --all
          
