name: Prepare for production Deploy ## comment#
on:
  push:
    branches:
      - dev

env:
  REGISTRY: mazenatefdevk8sk8sreg42h.azurecr.io
jobs:

  build:
    name: Generate a production Image 
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
        with: 
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      
      - name: Merge commit 
        run: |
          echo "MERGE_ID=$(git rev-parse HEAD^@ | cut -c 1-7 | sort | tr "\n" "_")" >> $GITHUB_ENV

      - name : test
        run : echo "hello "

